In [ ]:
!pip install transformers

In [56]:
from transformers import pipeline
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf

In [35]:
text_clasification = pipeline('sentiment-analysis',model = "j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

In [39]:
test1 = 'I am scared'
text_clasification(test1)

[[{'label': 'anger', 'score': 0.0007163436966948211},
  {'label': 'disgust', 'score': 0.00041105312993749976},
  {'label': 'fear', 'score': 0.9940180778503418},
  {'label': 'joy', 'score': 0.0007126834825612605},
  {'label': 'neutral', 'score': 0.0012325181160122156},
  {'label': 'sadness', 'score': 0.0020408525597304106},
  {'label': 'surprise', 'score': 0.0008686112705618143}]]

In [46]:
test2 = 'How could you dare?'
text_clasification(test2)

[[{'label': 'anger', 'score': 0.9583742022514343},
  {'label': 'disgust', 'score': 0.01923876814544201},
  {'label': 'fear', 'score': 0.00683360081166029},
  {'label': 'joy', 'score': 0.000912993389647454},
  {'label': 'neutral', 'score': 0.0030341146048158407},
  {'label': 'sadness', 'score': 0.002004524925723672},
  {'label': 'surprise', 'score': 0.009601854719221592}]]

In [41]:
#fill_mask = pipeline('fill-mask', model='bert-base-uncased')
#fill_mask("Hello, I'm a [MASK] teacher.")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.11413352936506271,
  'sequence': "hello, i'm a history teacher.",
  'token': 2381,
  'token_str': 'history'},
 {'score': 0.07028090208768845,
  'sequence': "hello, i'm a school teacher.",
  'token': 2082,
  'token_str': 'school'},
 {'score': 0.06983745843172073,
  'sequence': "hello, i'm a good teacher.",
  'token': 2204,
  'token_str': 'good'},
 {'score': 0.05665993690490723,
  'sequence': "hello, i'm a science teacher.",
  'token': 2671,
  'token_str': 'science'},
 {'score': 0.05624273791909218,
  'sequence': "hello, i'm a music teacher.",
  'token': 2189,
  'token_str': 'music'}]

In [ ]:
base_model = "j-hartmann/emotion-english-distilroberta-base"
model = TFAutoModelForSequenceClassification.from_pretrained(base_model, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(base_model)

In [47]:
inputs = tokenizer([test1, test2])
inputs

{'input_ids': [[0, 100, 524, 8265, 2], [0, 6179, 115, 47, 19046, 116, 2]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [54]:
inputs_with_padding = tokenizer([test1, test2], padding = True, truncation = True, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[    0,   100,   524,  8265,     2,     1,     1],
       [    0,  6179,   115,    47, 19046,   116,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [55]:
outputs = model(inputs_with_padding)
outputs

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(2, 7), dtype=float32, numpy=
                             array([[-1.2862786 , -1.8417155 ,  5.949072  , -1.291403  , -0.7436233 ,
                                     -0.23931551, -1.0935441 ],
                                    [ 4.723003  ,  0.8146871 , -0.22038527, -2.2332654 , -1.0323194 ,
                                     -1.4468334 ,  0.1197142 ]], dtype=float32)>)])

In [57]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[7.1634370e-04, 4.1105354e-04, 9.9401808e-01, 7.1268249e-04,
        1.2325193e-03, 2.0408535e-03, 8.6861051e-04],
       [9.5837450e-01, 1.9238679e-02, 6.8335934e-03, 9.1299060e-04,
        3.0341039e-03, 2.0045158e-03, 9.6017942e-03]], dtype=float32)>

In [71]:
predictions[0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9940181>

In [70]:
predictions[1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9583745>