In [10]:
from transformers import pipeline


In [16]:
classifier = pipeline('sentiment-analysis', model = "finiteautomata/bertweet-base-sentiment-analysis")

Downloading:   0%|          | 0.00/890 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/515M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/295 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/824k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/17.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

emoji is not installed, thus not converting emoticons or emojis into text. Please install emoji: pip3 install emoji


In [17]:
test1 = 'Good day today'
classifier(test1)

[{'label': 'POS', 'score': 0.9896361231803894}]

In [19]:
test2 = 'Are ypu ok?'
classifier(test2)

[{'label': 'NEU', 'score': 0.9539210200309753}]

In [20]:
test3 = 'OMG Stop it!!'
classifier(test3)

[{'label': 'NEG', 'score': 0.9483866691589355}]

In [22]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "finiteautomata/bertweet-base-sentiment-analysis"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFRobertaForSequenceClassification: ['roberta.embeddings.position_ids']
- This IS expected if you are initializing TFRobertaForSequenceClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaForSequenceClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFRobertaForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForSequenceClassification for predictions without further training.
emoji is not installed, thus not converting emoticons or emojis into text. Please

In [23]:
inputs = tokenizer([test1, test2, test3])

In [24]:
inputs

{'input_ids': [[0, 417, 93, 128, 2], [0, 533, 460, 18007, 6912, 21, 2], [0, 1115, 1267, 987, 41407, 12, 2]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [25]:
inputs_with_padding = tokenizer([test1, test2, test3], padding = True, truncation = True, max_length = 256, return_tensors="tf")

In [26]:
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[    0,   417,    93,   128,     2,     1,     1],
       [    0,   533,   460, 18007,  6912,    21,     2],
       [    0,  1115,  1267,   987, 41407,    12,     2]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [27]:
outputs = model(inputs_with_padding)

In [28]:
outputs

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
                             array([[-2.6532636 , -1.1107776 ,  3.6420333 ],
                                    [-3.1761181 ,  2.9909925 , -0.08361856],
                                    [ 2.5475233 , -0.66345465, -1.713704  ]], dtype=float32)>)])

In [29]:
import tensorflow as tf
predictions = tf.nn.softmax(outputs[0], axis=-1)

In [30]:
predictions

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.00182584, 0.008538  , 0.9896361 ],
       [0.00200065, 0.953921  , 0.04407839],
       [0.9483868 , 0.03823626, 0.01337698]], dtype=float32)>