In [237]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import re, string

import matplotlib.pyplot as plt
from wordcloud import WordCloud
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer


stop_words = stopwords.words('english')


train_url = 'https://drive.google.com/file/d/1Jg3l_AmdkfEIIiLAuwlwyybpXYt93Vvp/view?usp=sharing'
train_url_ = 'https://drive.google.com/uc?id=' + train_url.split('/')[-2]


test_url = 'https://drive.google.com/file/d/1Ytg9xAeZu4p-c6mcKDodHI3W7wLJ4sIo/view?usp=sharing'
test_url_ = 'https://drive.google.com/uc?id=' + test_url.split('/')[-2]
# df = pd.read_csv(url_)
# print(url.split('/')[-2])

print('my training link:', train_url_)
print('my testing link:', test_url_)


df.train = pd.read_csv(train_url_, header= None) # got the dataframe
df.test = pd.read_csv(test_url_, header= None)

#print('training file:\n', df.train.head(n = len(df.train)))


train_data_set = list(df.train[1])
test_data_set = list(df.test[1])


train_in_string = ''
for i in train_data_set:
    train_in_string += (' ' + i)
    
test_in_string = ''
for j in test_data_set:
    test_in_string += (' ' + j)
        
def cleaning(label):

    filtered = re.sub(r'[^\w\s]', '', label)
    filtered = re.sub("@\S+", "", filtered)
    filtered = re.sub("https*\S+", "", filtered)
    filtered = re.sub("\d", "", filtered)
    filtered = re.sub("#\S+", "", filtered)

    filtered = filtered.lower()
    #print(filtered)
    tokens = word_tokenize(filtered)
    #print(tokens)
    filtered_tokens = []
    for word in tokens:
        if word not in stop_words:
            filtered_tokens.append(word)#тут добавляю в новый список только те слова, которые не являются стоп словами
    #print(filtered_tokens)

    #print(filtered_tokens_set)
    lemmatizer = WordNetLemmatizer()
    #stemmer = PorterStemmer()
    # stemmed_tokens = [stemmer.stem(s) for s in filtered_tokens_set]
    # print('stemming:', stemmed_tokens)

    lemmatized = [lemmatizer.lemmatize(l) for l in filtered_tokens]
    lemmatizer = set(lemmatized)
    return lemmatizer


train_cleaned_data = cleaning(train_in_string)
test_cleaned_data = cleaning(test_in_string)
print(train_cleaned_data)
#print(test_cleaned_data)

    

my training link: https://drive.google.com/uc?id=1Jg3l_AmdkfEIIiLAuwlwyybpXYt93Vvp
my testing link: https://drive.google.com/uc?id=1Ytg9xAeZu4p-c6mcKDodHI3W7wLJ4sIo
{'drug', 'procedure', 'pemetrexed', 'phosphate', 'investigator', 'within', 'factor', 'investigational', 'syndrome', 'required', 'androgen', 'solid', 'line', 'eligible', 'opinion', 'willingness', 'rectal', 'ovarian', 'associated', 'pleural', 'prostate', 'infection', 'grade', 'tract', 'patient', 'less_than', 'risk', 'ctcae', 'considered', 'receive', 'concurrent', 'concomitant', 'subject', 'renal', 'intra', 'currently', 'node', 'pet', 'giant', 'cateder', 'de', 'terminology', 'limit', 'york', 'clearance', 'ect', 'hodgkin', 'malignant', 'metastasis', 'lymph', 'regional', 'nci', 'similar', 'positron_emission', 'melanoma', 'placement', 'pointes', 'jak', 'paclitaxel', 'characteristic', 'use', 'laboratory', 'able', 'cancer', 'clinic', 'status', 'colorectal', 'diagnosis', 'bone', 'pregnant', 'esophagus', 'creatinine', 'following', 'v

In [264]:
train_label = []
test_label = []

for label in list(df.train[0]):
    if label == '__label__0':
        train_label.append(0)
    if label == '__label__1':
        train_label.append(1)

for label_test in list(df.test[0]):
    if label_test == '__label__0':
        test_label.append(0)
    if label_test == '__label__1':
        test_label.append(1)

print(train_label)
print(test_label)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


In [265]:
y_train = np.asarray(train_label).astype("float32")
y_test = np.asarray(test_label).astype("float32")

print(train_label)
print(test_label)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


In [266]:
def vectorize(ten):
    vectorizer = CountVectorizer()
    sparse_matrix = vectorizer.fit_transform(ten)
    vectorizer.get_feature_names_out()
    
    return sparse_matrix.toarray()
    
train_vect = vectorize(train_cleaned_data) 
test_vect = vectorize(test_cleaned_data) 
print(train_vect)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [268]:


def embadding(sequences, dimension=10):
  
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        for j in sequence:
            results[i, j] = 1.
    return results

print(type(x_train))


<class 'numpy.ndarray'>


In [269]:
x_train = embadding(train_vect)

x_test = embadding(test_vect)
print(x_train)
print(type(x_train))

[[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]]
<class 'numpy.ndarray'>


In [270]:
import tensorflow as tf
from tensorflow.keras import layers

In [275]:
#creating a model with an activation function - relu
the_first_model = tf.keras.Sequential(name = 'model')# sequential() allows you to create models layer-by-layer 
 
the_first_model.add(layers.Dense(5, activation='relu', name = 'layer1'))

"""The function returns 0 if it receives any negative input,
but for any positive value x it returns that value back"""

the_first_model.add(layers.Dense(1, activation='sigmoid', name = 'layer3'))

print(the_first_model)

In [276]:
the_first_model.build(input_shape=(None, 3))
the_first_model.summary()

tf.config.run_functions_eagerly(True)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 5)                 20        
                                                                 
 layer3 (Dense)              (None, 1)                 6         
                                                                 
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________


In [277]:
the_first_model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"], run_eagerly=True)


print(type(x_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [278]:
history = the_first_model.fit(x_train,
                   y_train,
                    epochs=10,
                    batch_size=300,
                    validation_split=2,
                    shuffle = True,
                    verbose =5)


Epoch 1/10


ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

In [279]:
# history = the_first_model.fit(train_embadding, train_label, epochs=10, batch_size=11, validation_split=2, shuffle = True, verbose = 2)

In [280]:
print(the_first_model.summary())

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 5)                 20        
                                                                 
 layer3 (Dense)              (None, 1)                 6         
                                                                 
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________
None
