In [6]:
# Transformers installation
#pip install transformers

from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

In [7]:
txt_1 = 'Football is the most exciting and popular game in the world'
classifier(txt_1)

[{'label': 'POSITIVE', 'score': 0.9998573064804077}]

In [4]:
pip install transformers

     |████████████████████████████████| 3.5 MB 13.5 MB/s 
     |████████████████████████████████| 67 kB 3.8 MB/s 
     |████████████████████████████████| 596 kB 56.8 MB/s 
     |████████████████████████████████| 895 kB 55.2 MB/s 
     |████████████████████████████████| 6.8 MB 50.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [8]:
txt_2 = 'The weather is unpredictable around here'
classifier(txt_2)

[{'label': 'POSITIVE', 'score': 0.695080041885376}]

In [9]:
txt_3 = 'I am in love with my cat'
classifier(txt_3)

[{'label': 'POSITIVE', 'score': 0.999078631401062}]

In [15]:
txt_4 = 'My education process is pretty nice but a bit complicated'
classifier(txt_4)

[{'label': 'NEGATIVE', 'score': 0.9234269261360168}]

In [14]:
txt_5 = 'My education process is pretty nice'
classifier(txt_5)

[{'label': 'POSITIVE', 'score': 0.9998378753662109}]

In [16]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)


Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [17]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

txt_1 = 'I do not like coffee'
classifier(txt_1)
txt_2 = 'I hate buckwheat'
classifier(txt_2)

inputs = tokenizer([txt_1, txt_2])

inputs

{'input_ids': [[101, 1045, 2079, 2025, 2066, 4157, 102], [101, 1045, 5223, 10131, 2860, 20192, 2102, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [19]:
inputs_with_padding = tokenizer([txt_1, txt_2], padding = True, truncation = True, max_length = 256, return_tensors="tf")

In [20]:
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[  101,  1045,  2079,  2025,  2066,  4157,   102,     0],
       [  101,  1045,  5223, 10131,  2860, 20192,  2102,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [21]:
outputs = model(inputs_with_padding)

In [22]:
outputs


TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
                             array([[ 3.0810382, -2.5822375],
                                    [ 2.8234954, -2.3580997]], dtype=float32)>)])

In [23]:
import tensorflow as tf
predictions = tf.nn.softmax(outputs[0], axis=-1)

In [24]:
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.99654084, 0.00345912],
       [0.99441236, 0.00558764]], dtype=float32)>

In [32]:
fill_mask_clas = pipeline('fill-mask')
fill_mask_c = pipeline('fill-mask', model = 'camembert-base')

fill_mask_c('I love <mask>')[0],fill_mask_c('He loves <mask> ')[0]



No model was supplied, defaulted to distilroberta-base (https://huggingface.co/distilroberta-base)


({'score': 0.26956185698509216,
  'sequence': 'I love you',
  'token': 4835,
  'token_str': 'you'},
 {'score': 0.1908416599035263,
  'sequence': 'He loves it',
  'token': 6434,
  'token_str': 'it'})

In [36]:
from transformers import pipeline
classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli")

sequence_to_classify = "one day I will see the world"
candidate_labels = ['travel', 'cooking', 'dancing']
classifier(sequence_to_classify, candidate_labels)

{'labels': ['travel', 'dancing', 'cooking'],
 'scores': [0.9938650727272034, 0.0032737976871430874, 0.002861043205484748],
 'sequence': 'one day I will see the world'}

In [38]:
sequence_to_classify_1 = "My family is my soul"
candidate_labels_1 = ['mother', 'granny', 'heart', 'travel', 'cooking']
classifier(sequence_to_classify_1, candidate_labels_1)

{'labels': ['heart', 'mother', 'granny', 'cooking', 'travel'],
 'scores': [0.9399558901786804,
  0.03917044401168823,
  0.014205826446413994,
  0.0038584053982049227,
  0.0028094493318349123],
 'sequence': 'My family is my soul'}