In [56]:
from transformers import pipeline
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf

In [81]:
text_clasification = pipeline('sentiment-analysis', model = "j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

In [74]:
test1 = 'I am scared!'
text_clasification(test1)

[[{'label': 'anger', 'score': 0.0023145517334342003},
  {'label': 'disgust', 'score': 0.0007054118323139846},
  {'label': 'fear', 'score': 0.9890506267547607},
  {'label': 'joy', 'score': 0.0009633987210690975},
  {'label': 'neutral', 'score': 0.001985208597034216},
  {'label': 'sadness', 'score': 0.0025366507470607758},
  {'label': 'surprise', 'score': 0.002444098936393857}]]

In [46]:
test2 = 'How could you dare?'
text_clasification(test2)

[[{'label': 'anger', 'score': 0.9583742022514343},
  {'label': 'disgust', 'score': 0.01923876814544201},
  {'label': 'fear', 'score': 0.00683360081166029},
  {'label': 'joy', 'score': 0.000912993389647454},
  {'label': 'neutral', 'score': 0.0030341146048158407},
  {'label': 'sadness', 'score': 0.002004524925723672},
  {'label': 'surprise', 'score': 0.009601854719221592}]]

In [73]:
#fill_mask = pipeline('fill-mask', model='bert-base-uncased')
#fill_mask("I am [MASK] scared")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.5903838872909546,
  'sequence': 'i am so scared',
  'token': 2061,
  'token_str': 'so'},
 {'score': 0.14422643184661865,
  'sequence': 'i am not scared',
  'token': 2025,
  'token_str': 'not'},
 {'score': 0.037188570946455,
  'sequence': 'i am still scared',
  'token': 2145,
  'token_str': 'still'},
 {'score': 0.02825786918401718,
  'sequence': 'i am really scared',
  'token': 2428,
  'token_str': 'really'},
 {'score': 0.027339352294802666,
  'sequence': 'i am just scared',
  'token': 2074,
  'token_str': 'just'}]

In [ ]:
base_model = "j-hartmann/emotion-english-distilroberta-base"
model = TFAutoModelForSequenceClassification.from_pretrained(base_model, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(base_model)

In [75]:
inputs = tokenizer([test1, test2])
inputs

{'input_ids': [[0, 100, 524, 8265, 328, 2], [0, 6179, 115, 47, 19046, 116, 2]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [76]:
inputs_with_padding = tokenizer([test1, test2], padding = True, truncation = True, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[    0,   100,   524,  8265,   328,     2,     1],
       [    0,  6179,   115,    47, 19046,   116,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [77]:
outputs = model(inputs_with_padding)
outputs

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(2, 7), dtype=float32, numpy=
                             array([[-0.6005598 , -1.7887484 ,  5.4569693 , -1.4770631 , -0.7540513 ,
                                     -0.50893027, -0.5460996 ],
                                    [ 4.723003  ,  0.8146871 , -0.22038527, -2.2332654 , -1.0323194 ,
                                     -1.4468334 ,  0.1197142 ]], dtype=float32)>)])

In [78]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[2.3145527e-03, 7.0541282e-04, 9.8905051e-01, 9.6339959e-04,
        1.9852107e-03, 2.5366540e-03, 2.4440989e-03],
       [9.5837450e-01, 1.9238679e-02, 6.8335934e-03, 9.1299060e-04,
        3.0341039e-03, 2.0045158e-03, 9.6017942e-03]], dtype=float32)>

In [79]:
predictions[0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9890505>

In [80]:
predictions[1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9583745>